version: '3.8'

networks:  
  inner-network:  
    name: inner-network  
    driver: bridge
    
services:
  job-database:
    container_name: job-database
    image: mysql:5.7
    networks:
      - inner-network
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'job_db'
      MYSQL_USER: 'job_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3306
      
  dept-database:
    container_name: dept-database
    image: mysql:5.7
    networks:
      - inner-network
    ports:
      - '3307:3307'
    expose:
      - '3307' 
    environment:
      MYSQL_DATABASE: 'dept_db'
      MYSQL_USER: 'dept_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3307
      
  emp-database:
    container_name: emp-database
    image: mysql:5.7
    networks:
      - inner-network
    ports:
      - '3308:3308'
    expose:
      - '3308'      
    environment:
      MYSQL_DATABASE: 'emp_db'
      MYSQL_USER: 'emp_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3308
      
  naming-server:
    container_name: naming-server
    image: naming-server:0.0.1-SNAPSHOT
    ports:
      - '8761:8761'
    networks:
      - inner-network
    environment:
      server.port: 8761
      eureka.instance.hostname: naming-server
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      
  cloud-config:
    container_name: cloud-config
    image: cloud-config:0.0.1-SNAPSHOT
    ports:
      - '8070:8070'
    networks:
      - inner-network
    depends_on:
     - naming-server
    environment:
      server.port: 8070
      
  job-service:
    container_name: job-microservice
    image: job-microservice:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - '8081:8081'
    networks:
      - inner-network
    depends_on:
      - naming-server
      - cloud-config
      - job-database
    environment:
      server.port: 8081
      spring.config.import: 'configserver:http://cloud-config:8070/'
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.datasource.url: jdbc:mysql://job-database:3306/job_db
      spring.datasource.driver-class-name: com.mysql.jdbc.Driver
      spring.datasource.username: job_user
      spring.datasource.password: password
      spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      spring.jpa.hibernate.ddl-auto: update
      
  dept-service:
    container_name: dept-microservice
    image: dept-microservice:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - '8083:8083'
    networks:
      - inner-network
    depends_on:
      - naming-server
      - cloud-config
      - dept-database
    environment:
      server.port: 8083
      spring.config.import: 'configserver:http://cloud-config:8070/'
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.datasource.url: jdbc:mysql://dept-database:3307/dept_db
      spring.datasource.driver-class-name: com.mysql.jdbc.Driver
      spring.datasource.username: dept_user
      spring.datasource.password: password
      spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      spring.jpa.hibernate.ddl-auto: update
      
  emp-service:
    container_name: emp-microservice
    image: emp-microservice:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - '8082:8082'
    networks:
      - inner-network
    depends_on:
      - naming-server
      - cloud-config
      - dept-service
      - job-service
      - emp-database
    environment:
      server.port: 8082
      spring.config.import: 'configserver:http://cloud-config:8070/'
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.datasource.url: jdbc:mysql://emp-database:3308/emp_db
      spring.datasource.driver-class-name: com.mysql.jdbc.Driver
      spring.datasource.username: emp_user
      spring.datasource.password: password
      spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      spring.jpa.hibernate.ddl-auto: update