version: '3.7'

services:
  naming-server:
    container_name: naming-server
    image: naming-server:0.0.1-SNAPSHOT
    network_mode: host
    ports:
      - "8761:8761"
  cloud-config:
    container_name: cloud-config
    image: cloud-config:0.0.1-SNAPSHOT
    network_mode: host
    ports:
      - "8070:8070"
    depends_on:
     - naming-server
  job-service:
    container_name: job-microservice
    image: job-microservice:0.0.1-SNAPSHOT
    network_mode: host
    ports:
      - "8081:8081"
    depends_on:
      - naming-server
      - cloud-config
  dept-service:
    container_name: dept-microservice
    image: dept-microservice:0.0.1-SNAPSHOT
    network_mode: host
    ports:
      - "8083:8083"
    depends_on:
      - naming-server
      - cloud-config
  emp-service:
    container_name: emp-microservice
    image: emp-microservice:0.0.1-SNAPSHOT
    network_mode: host
    ports:
      - "8082:8082"
    depends_on:
      - naming-server
      - cloud-config
      - dept-service
      - job-service
